version: '2'
services:
    flair-engine:
        networks:
        - flair-network
        image: fbiengine
        environment:
        - CONFIG_URI=http://localhost:8761
        - EUREKA_URL=http://admin:admin@localhost:8761/eureka
        - JHIPSTER_SLEEP=20
        - SPRING_PROFILES_ACTIVE=prod,grpc,tls
        - POSTGRES_URI=flair-engine-pgsql:5432

    flair-engine-pgsql:
        networks:
        - flair-network
        extends:
            file: storage.yml
            service: flair-engine-pgsql

networks:
    flair-network:
        driver: bridge
