version: '2'


services:
    testdata:
        image: manoj10/postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: postgres
        labels:
            environment: testing
        ports:
            - "5429:5430"