version: "2"
services:
    flair-engine:
        image: ${DOCKER_REGISTRY_URL}/flair-engine:latest-${GIT_LOCAL_BRANCH}
        labels:
            purpose: Bankend engine
            environment: staging
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://${EUREKA_CRED}@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=20
            - SPRING_PROFILES_ACTIVE=prod,http
            - POSTGRES_URI=flair-engine-pgsql:5432
        mem_limit: 1024m
        # logging:
        #     driver: "fluentd"
        #     options:
        #         fluentd-address: localhost:24224
        #         tag: flair-engine-http-staging

    flair-engine-grpc:
        image: ${DOCKER_REGISTRY_URL}/flair-engine:latest-${GIT_LOCAL_BRANCH}
        labels:
            purpose: Bankend engine
            environment: staging
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://${EUREKA_CRED}@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=20
            - SPRING_PROFILES_ACTIVE=prod,grpc
            - POSTGRES_URI=flair-engine-pgsql:5432
            - GRPC_CERT=server.crt
            - GRPC_KEY=server.key
        mem_limit: 1024m
        # logging:
        #     driver: "fluentd"
        #     options:
        #         fluentd-address: localhost:24224
        #         tag: flair-engine-grpc-staging

    flair-engine-pgsql:
        container_name: "staging-flair-engine-postgresql"
        image: ${DOCKER_REGISTRY_URL}/flair-engine-pgsql:latest-${GIT_LOCAL_BRANCH}
        labels:
            purpose: Flair engine store
            environment: staging
        command: -c ssl=on -c ssl_cert_file=/etc/pki/tls/certs/fbiengine-psql.pem -c ssl_key_file=/etc/pki/tls/private/fbiengine-psql.key
        # volumes:
        #  - /home/vizcentric/Documents/data/postgres/flair-engine:/var/lib/postgresql/data
        # ports:
        #     - 5430:5432
        environment:
            - POSTGRES_USER=${PGSQL_USER}
            - POSTGRES_PASSWORD=${PGSQL_PASS}
            - POSTGRES_DB=fbiengine
        mem_limit: 1024m
        # logging:
        #     driver: "fluentd"
        #     options:
        #         fluentd-address: localhost:24224
        #         tag: flair-engine-pgsql-staging

networks:
    default:
        external:
            name: staging
