version: "2"
services:
    flair-engine:
        image: flairbi/flair-engine
        labels:
            purpose: Bankend engine
            environment: staging
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=20
            - SPRING_PROFILES_ACTIVE=prod,http
            - POSTGRES_URI=flair-engine-pgsql:5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=admin
        networks:
        - flair-network

    flair-engine-grpc:
        image: flairbi/flair-engine
        labels:
            purpose: Bankend engine
            environment: staging
        networks:
        - flair-network
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=20
            - SPRING_PROFILES_ACTIVE=prod,grpc
            - POSTGRES_URI=flair-engine-pgsql:5432
            - GRPC_CERT=server.crt
            - GRPC_KEY=server.key
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=admin

    flair-engine-pgsql:
        image: flairbi/flair-engine-pgsql
        labels:
            purpose: Flair engine store
            environment: staging
        command: -c ssl=on -c ssl_cert_file=/etc/pki/tls/certs/fbiengine-psql.pem -c ssl_key_file=/etc/pki/tls/private/fbiengine-psql.key
        networks:
        - flair-network
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=fbiengine

networks:
    flair-network:
        external:
            name: flair-network
