version: '2'
services:
    flair-engine-pgsql:
        container_name: flair-engine-pgsql
        build: ./flair-engine-pgsql
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fbiengine
        command: -c ssl=on -c ssl_cert_file=/etc/pki/tls/certs/fbiengine-psql.pem -c ssl_key_file=/etc/pki/tls/private/fbiengine-psql.key
        ports:
        - 5430:5432
