version: '2'
services:
    flair-engine-pgsql:
        container_name: "test-postgres-backend"
        image: flairbi/flair-engine-pgsql:latest
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fbiengine
        ports:
        - 5432:5432
        networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik